; Realtime family to ODBC backend mappings.
; DSN name must match the section in res_odbc.conf.

[settings]
ps_endpoints => odbc,asterisk_cfg,ps_endpoints
ps_aors => odbc,asterisk_cfg,ps_aors
ps_auths => odbc,asterisk_cfg,ps_auths
ps_endpoint_id_ips => odbc,asterisk_cfg,ps_endpoint_id_ips
ps_domain_aliases => odbc,asterisk_cfg,ps_domain_aliases
