; Sorcery mappings for realtime PJSIP objects.
; Requires extconfig.conf + res_odbc.conf mapping.

[res_pjsip]
endpoint=realtime,ps_endpoints
aor=realtime,ps_aors
auth=realtime,ps_auths
identify=realtime,ps_endpoint_id_ips
domain_alias=realtime,ps_domain_aliases
